# Generated by Django 4.2.6 on 2023-10-23 19:25

from django.db import migrations
from django.db.migrations import RunPython


def add_package_types(apps, schema_editor):
    PackageType = apps.get_model("delivery", "PackageType")
    types = [
        PackageType(name="clothes"),
        PackageType(name="electronics"),
        PackageType(name="other")
    ]
    PackageType.objects.bulk_create(types)


class Migration(migrations.Migration):
    """Adds package types"""
    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        RunPython(add_package_types)
    ]