version: '3.7'
services:
  celery:
    depends_on:
      - mysql_db
      - redis
      - django
    restart: always
    container_name: celery

    working_dir: /app
    user: django
    command: celery -A radelta worker -l INFO -Q main,celery -B --pidfile="./run/celery/%n.pid"
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env

  django:
    depends_on:
      - mysql_db
      - redis
    restart: always
    container_name: django

    working_dir: /app
    user: django
    command: python manage.py runserver 0.0.0.0:8000

    build:
      dockerfile: ./Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - .env


  mysql_db:
    image: mysql:8
    restart: always
    container_name: mysql_db

    env_file:
      - .env
    volumes:
      - ./dbdata:/var/lib/mysql/


  redis:
    image: redis:alpine
    container_name: redis


